exclude_results:
  - code: aws-iam-no-policy-wildcards
    where:
      resource: "aws_iam_role_policy.vpc_flow_logs"

  - code: aws-iam-no-policy-wildcards
    where:
      resource: "aws_iam_role_policy.lambda_inline"